server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: entrada-service
  jpa:
    show-sql: true
    hibernate:
      dialect: PostgreSQL9Dialect
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    dbname: entrada

    url: jdbc:postgresql://localhost:5432/entrada
    username: postgres
    password: 1234