apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrada-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entrada-service
  template:
    metadata:
      labels:
        app: entrada-service
    spec:
      containers:
        - name: entrada-service
          image: ijynx1/entrada-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-entrada:5432/entrada
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: salida-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salida-service
  template:
    metadata:
      labels:
        app: salida-service
    spec:
      containers:
        - name: salida-service
          image: ijynx1/salida-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-salida:5432/salida
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movimientos-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movimientos-service
  template:
    metadata:
      labels:
        app: movimientos-service
    spec:
      containers:
        - name: movimientos-service
          image: ijynx1/movimientos-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-movimientos:5432/movimientos
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
---