apiVersion: apps/v1
kind: Deployment
metadata:
  name: acopio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acopio-service
  template:
    metadata:
      labels:
        app: acopio-service
    spec:
      containers:
        - name: acopio-service
          image: ijynx1/acopio-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-acopio:5432/acopio
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proveedor-service
  template:
    metadata:
      labels:
        app: proveedor-service
    spec:
      containers:
        - name: proveedor-service
          image: ijynx1/proveedor-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-proveedor:5432/proveedor
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laboratorio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laboratorio-service
  template:
    metadata:
      labels:
        app: laboratorio-service
    spec:
      containers:
        - name: laboratorio-service
          image: ijynx1/laboratorio-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-laboratorio:5432/laboratorio
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagos-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagos-service
  template:
    metadata:
      labels:
        app: pagos-service
    spec:
      containers:
        - name: pagos-service
          image: ijynx1/pagos-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-pagos:5432/pagos
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
---