apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-entrada
  labels:
    app: postgres-entrada
spec:
  selector:
    matchLabels:
      app: postgres-entrada
  template:
    metadata:
      labels:
        app: postgres-entrada
    spec:
      containers:
        - name: postgres-entrada
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "entrada"
          volumeMounts:
            - name: postgres-entrada-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-entrada-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-entrada-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-entrada-pv-claim
  labels:
    app: postgres-entrada
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-entrada
  labels:
    app: postgres-entrada
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-entrada
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: entrada-db
data:
  name: "entrada"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-salida
  labels:
    app: postgres-salida
spec:
  selector:
    matchLabels:
      app: postgres-salida
  template:
    metadata:
      labels:
        app: postgres-salida
    spec:
      containers:
        - name: postgres-salida
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "salida"
          volumeMounts:
            - name: postgres-salida-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-salida-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-salida-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-salida-pv-claim
  labels:
    app: postgres-salida
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-salida
  labels:
    app: postgres-salida
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-salida
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: salida-db
data:
  name: "salida"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-movimientos
  labels:
    app: postgres-movimientos
spec:
  selector:
    matchLabels:
      app: postgres-movimientos
  template:
    metadata:
      labels:
        app: postgres-movimientos
    spec:
      containers:
        - name: postgres-movimientos
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "movimientos"
          volumeMounts:
            - name: postgres-movimientos-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-movimientos-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-movimientos-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-movimientos-pv-claim
  labels:
    app: postgres-movimientos
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-movimientos
  labels:
    app: postgres-movimientos
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-movimientos
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: movimientos-db
data:
  name: "movimientos"
---